language: cpp
sudo: false
addons:
    apt:
        packages:
            - g++
            - build-essential
            - automake
            - autoconf
            - make
            - libtool
            - shtool
            - autogen
script: ./configure && make
