language: cpp
sudo: false
addons:
    apt:
        packages:
            - g++
            - build-essential
            - automake
            - autoconf
            - make
            - libtool
            - shtool
            - autogen
            - intltool
script: cd ./libs/libarchive-3.1.2/ && autoreconf -f && cd ../../ && ./configure && make
