language: cpp
sudo: false
addons:
    apt:
        packages:
            - g++-4.9
            - libcurl14-openssl-dev
            - libarchive-dev
script: aclocal && autoconf && automake --add-missing && ./configure && make
