language: c
compiler: gcc
dist: trusty

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y valgrind lcov autopoint flex gettext
    - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

script:
    - make init
    - make
    - make clean check
    - make coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)
